# Generated by Django 4.2.3 on 2023-07-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('age_rectriction', models.CharField(choices=[('E', 'Everyone'), ('T', 'Teen'), ('M', 'Mature')], max_length=1)),
                ('year_released', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
