# Generated by Django 4.2.3 on 2023-07-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='age_rectriction',
        ),
    ]
