# Generated by Django 4.2.3 on 2023-07-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_age_rectriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='games/default.jpg', upload_to='images/'),
        ),
    ]
