# Generated by Django 4.2.3 on 2023-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
    ]
